// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repositories

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	HashPassword string    `json:"hash_password"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
