// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package repositories

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (workspace_id, created_by, assignee_id, title, description, status, priority, due_date)
    VALUES ($1, $2, $3, $4, $5, COALESCE($6::task_status, 'TODO'::task_status), COALESCE($7::task_priority, 'MEDIUM'::task_priority), $8)
RETURNING
    id, workspace_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	WorkspaceID uuid.UUID    `json:"workspace_id"`
	CreatedBy   uuid.UUID    `json:"created_by"`
	AssigneeID  *uuid.UUID   `json:"assignee_id"`
	Title       string       `json:"title"`
	Description *string      `json:"description"`
	Column6     TaskStatus   `json:"column_6"`
	Column7     TaskPriority `json:"column_7"`
	DueDate     *time.Time   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Column6,
		arg.Column7,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    id, workspace_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
FROM
    tasks
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskByAssignee = `-- name: ListTaskByAssignee :many
SELECT
    id, workspace_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
FROM
    tasks
WHERE
    assignee_id = $1
    AND workspace_id = $2
ORDER BY
    created_at DESC
`

type ListTaskByAssigneeParams struct {
	AssigneeID  *uuid.UUID `json:"assignee_id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
}

func (q *Queries) ListTaskByAssignee(ctx context.Context, arg ListTaskByAssigneeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTaskByAssignee, arg.AssigneeID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByWorkspace = `-- name: ListTasksByWorkspace :many
SELECT
    id, workspace_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
FROM
    tasks
WHERE
    workspace_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) ListTasksByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE
    tasks
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    assignee_id = COALESCE($4, assignee_id),
    status = COALESCE($5::task_status, status),
    priority = COALESCE($6::task_priority, priority),
    due_date = COALESCE($7, due_date),
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, workspace_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description *string      `json:"description"`
	AssigneeID  *uuid.UUID   `json:"assignee_id"`
	Column5     TaskStatus   `json:"column_5"`
	Column6     TaskPriority `json:"column_6"`
	DueDate     *time.Time   `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.Column5,
		arg.Column6,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
